### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by joaoandrefaria** [SmartBlug/grafana-csv-datasource#1]
After following all steps, I start PythonServer without erros but it gives me a 404 Not Found Error.

"Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

Can you help?

**Comment by SudhaViswanathan-123** [comment]
I am getting same error after start python server.
"Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
Please can you help me
